[package]
name = "nvim-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace.dependencies]
libc = "0.2.169"
panics = { path = "./panics" }

[workspace]
members = [ "panics", "nvim-types"]
