[package]
name = "nvim-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nvim-types = { workspace = true }
nvim-funcs = { workspace = true }
macros = { workspace = true }
plugin = { path = "./plugin" }

[workspace.dependencies]
libc = { version = "0.2.169", default-features = false }
bytemuck = { version = "1.22.0", features = ["must_cast"] }
panics = { path = "./panics" }
nvim-types = { path = "./nvim-types/" }
nvim-funcs = { path = "./nvim-funcs/" }
macros = { path = "./macros/" }

[dev-dependencies]
trybuild = { version = "1.0.101" }

[workspace]
members = [ "panics", "nvim-types", "nvim-funcs", "plugin", "macros"]

[profile.dev]
incremental = true

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1
