# recommended by trybuild
[tasks.install-rust-src]
install_crate = { rustup_component_name = "rust-src" }

[tasks.install-miri]
toolchain = "nightly"    
install_crate = { rustup_component_name = "miri" }

[tasks.test]
workspace=false
dependencies = ["miri-tests", "normal-tests"]

[tasks.normal-tests]
dependencies = ["install-rust-src"]
command = "cargo"
# no need to check nvim-types and macros, we run them with miri
args = ["test", "--workspace", "--exclude", "macros", "--features", "testing"]


[tasks.miri-tests]
dependencies = ["install-miri"]
toolchain = "nightly"
command = "cargo"
args = ["miri", "test"]
