pub mod array;
pub mod borrowed;
pub mod buffer;
pub mod call_site;
pub mod dictionary;
pub mod error;
pub mod hl_group;
pub mod kvec;
pub mod lua_ref;
pub mod namespace;
pub mod object;
pub mod string;
pub mod tab_page;
pub mod window;

pub type Integer = i64;
pub type Boolean = bool;
pub type Float = libc::c_double;
pub type HandleT = libc::c_int;
pub type HLGroupIDT = Integer;
pub type LuaRefT = libc::c_int;
