[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvimium = { path = "../../" }

[features]
# You will definitely want to add a testing feature gate to avoid terrible compile times
default = ["testing"]
testing = ["nvimium/testing"]
