[package]
name = "nvim-types"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { workspace = true }
libc = { workspace = true }
panics = { workspace = true }
macros = { workspace = true }
mlua-sys = { workspace = true }
