[package]
name = "nvim-types"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { workspace = true }
libc = { workspace = true }
panics = { workspace = true }
macros = { workspace = true }
bytemuck = { workspace = true }
mlua-sys = { version = "0.6.7", features = ["lua51"] }
