[package]
name = "nvim-types"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { workspace = true }
panics = { workspace = true }
macros = { workspace = true }
bytemuck = { workspace = true }
