pub mod array;
pub(crate) mod borrowed;
pub mod buffer;
pub mod call_site;
pub mod dictionary;
pub mod error;
pub mod hl_group;
pub mod kvec;
pub mod lua_ref;
pub mod namespace;
pub mod object;
pub mod string;
pub mod tab_page;
pub mod window;

pub type Integer = i64;
pub type Boolean = bool;
pub type Float = libc::c_double;
pub type HandleT = libc::c_int;
pub type HLGroupIDT = Integer;
pub type LuaRefT = libc::c_int;

pub use array::Array;
pub use buffer::Buffer;
pub use call_site::Channel;
pub use dictionary::{Dictionary, KeyValuePair};
pub use error::Error;
pub use hl_group::HlGroupId;
pub use kvec::KVec;
pub use lua_ref::LuaRef;
pub use namespace::NameSpace;
pub use object::Object;
pub use string::{AsThinString, OwnedThinString, String, ThinString};
pub use tab_page::TabPage;
pub use window::Window;
