name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
    - name: Install Lua 5.1
      run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends liblua5.4-dev liblua5.3-dev liblua5.2-dev liblua5.1-0-dev libluajit-5.1-dev
    - name: Install rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Run CI
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: cargo make test
